# Generated by Django 4.1 on 2022-09-09 12:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=40, validators=[django.core.validators.RegexValidator(message='your email', regex='(^[A-Za-z0-9]+[\\w_]+.[\\w_]+@[0-9A-Za-z]+\\.[a-z]{2,7}$)')])),
                ('name', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name': 'MySubscriber',
                'verbose_name_plural': 'A lot of Subscribers',
            },
        ),
    ]
